### ISSUE TITLE
Create User entity

### ISSUE THREAD

**Issue by LeandroHamaguchi** [stevenluo624/CSC207Project192#15]
Create User entity class according to the [blueprint](https://docs.google.com/document/d/1uWU11kSJSQEOx6GCa5JlFfYCSrYpRor5EGN_BHSNSaI/edit?usp=sharing) and the [CA Lab code](https://github.com/LeandroHamaguchi/CAUserLogin).
Also, check other lab codes and follow CA and SOLID principles for marks.

**Comment by codymavok** [comment]
Edit 1:
- Made user an interface for now
